definitions:
  controller.Controller:
    type: object
info:
  contact: {}
paths:
  /acc/v01/ok:
    get:
      consumes:
      - application/json
      description: api test를 위한 기능.
      parameters:
      - description: User name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call GetOK, return ok by json.
swagger: "2.0"
